
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQEQ = 9;
  public static final int BEGIN = 2;
  public static final int END = 3;
  public static final int STRING_LITERAL = 7;
  public static final int PLUS = 10;
  public static final int EQ = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IDENTIFIER = 5;
  public static final int ALIAS = 4;
  public static final int INTEGER_LITERAL = 6;
public static final int LEFT_BRACE = 11;
public static final int RIGHT_BRACE = 12;
public static final int LEFT_PAREN = 13;
public static final int RIGHT_PAREN = 14;
public static final int DOT = 15;
public static final int SEMICOLON = 16;
public static final int LEFT_BRACKET = 17;
public static final int RIGHT_BRACKET = 18;
public static final int AND = 19;
public static final int BREAK = 20;
public static final int CASE = 21;
public static final int CLASS = 22;
public static final int DEF = 23;
public static final int DEFINED = 24;
public static final int DO = 25;
public static final int ELSE = 26;
public static final int ELSIF = 27;
public static final int ENSURE = 28;
public static final int FALSE = 29;
public static final int FOR = 30;
public static final int IF = 31;
public static final int IN = 32;
public static final int MODULE = 33;
public static final int NEXT = 34;
public static final int NIL = 35;
public static final int NOT = 36;
public static final int OR = 37;
public static final int REDO = 38;
public static final int RESCUE = 39;
public static final int RETRY = 40;
public static final int RETURN = 41;
public static final int SELF = 42;
public static final int SUPER =43;
public static final int THEN = 44;
public static final int TRUE = 45;
public static final int UNDEF = 46;
public static final int UNLESS = 47;
public static final int UNTIL= 48;
public static final int WHEN = 49;
public static final int WHILE= 50;
public static final int YIELD = 51;
public static final int MOD = 52;
public static final int NEQ = 53;
public static final int GT = 54;
public static final int LT = 55;
public static final int GE= 56;
public static final int LE = 57;
public static final int C_COMPARISON = 58;
public static final int AND_OP = 59;
public static final int OR_OP = 60;
public static final int NOT_OP = 61;
public static final int MINUS = 62;
public static final int MULTIPLY = 63;
public static final int DIVIDE = 64;
public static final int EXP = 65;
public static final int PLUS_AS = 66;
public static final int MINUS_AS = 67;
public static final int MULTIPLY_AS = 68;
public static final int DIVIDE_AS = 69;
public static final int MOD_AS = 70;
public static final int EXP_AS = 71;
public static final int AND_BIT = 72;
public static final int OR_BIT = 73;
public static final int XOR_BIT =74;
public static final int NOT_BIT = 75;
public static final int QUESTION = 76;
public static final int COMMA = 77;
public static final int COLON = 78;
public static final int DOLLAR = 79;
public static final int AT = 80;
public static final int ATAT = 81;


  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "ALIAS",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "EQ",
  "EQEQ",
  "PLUS",
"LEFT_BRACE",
"RIGHT_BRACE",
"LEFT_PAREN",
"RIGHT_PAREN",
"DOT",
"SEMICOLON",
"LEFT_BRACKET",
"RIGHT_BRACKET",
"AND",
"BREAK",
"CASE",
"DEF",
"DEFINED",
"DO",
"ELSE",
"ELSIF",
"ENSURE",
"FALSE",
"FOR",
"IF",
"IN",
"MODULE",
"NEXT",
"NIL",
"NOT",
"OR",
"REDO",
"RESCUE",
"RETRY",
"RETURN",
"SELF",
"SUPER",
"THEN",
"TRUE",
"UNDEF",
"UNLESS",
"UNTIL",
"WHEN",
"WHILE",
"YIELD",
"MOD",
"NEQ",
"GT",
"LT",
"GE",
"LE",
"C_COMPARISON",
"AND_OP",
"OR_OP",
"NOT_OP",
"MINUS",
"MULTIPLY",
"DIVIDE",
"EXP",
"PLUS_AS",
"MINUS_AS",
"MULTIPLY_AS",
"DIVIDE_AS",
"MOD_AS",
"EXP_AS",
"AND_BIT",
"OR_BIT",
"XOR_BIT",
"NOT_BIT",
"QUESTION",
"COMMA",
"COLON",
"DOLLAR",
"AT",
"ATAT"

  };
}

